### ISSUE TITLE
SUGGESTION: Put all pastes into a `knowledge` folder

### ISSUE THREAD

**Issue by MMK21Hub** [SheepCommander/KnowledgeBase#16]
**The problem:**
For someone browsing this repo, it is unclear what the `remaking-tools` folder is for, as it is in the root of KnowledgeBase, along with the folders that contain the different types of pastes.

I propose this:
```
📁 knowledge
	📁 faq
	📁 text-editor-plugins
	📁 pros-cons
	etc.
📁 remaking-tools
📄 .gitignore
📄 Contributing.md
📄 README.md
```

This could also be useful in the future. E.g if we decide to make a custom bot, its source would go in a `📁bot` folder.

We may also want to rename `📁remaking-tools` to something like `utilities`?

**Comment by MMK21Hub** [comment]
As much as I hate to suggest _another_ change to the folder structure, it's better to get this done now.

If Sheep thinks "nah" then that's fine too.

**Comment by Anthony2be** [comment]
I was thinking about the bot folder

**Comment by SheepCommander** [comment]
Actually that does sound like a good idea. We haven't made an announcement yet so we still have time to just change stuff

**Comment by SheepCommander** [comment]
imma close this now. We ended up going for 1.16.4 btw
